Update maven-build.yml

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -22,30 +22,6 @@ jobs:
               echo "Git is already installed."
           fi
 
-      # - name: Check for Docker
-      #   run: |
-      #     if ! command -v docker &> /dev/null
-      #     then
-      #         echo "Docker not found, installing..."
-      #         sudo apt-get update -y
-      #         sudo apt-get install -y docker.io
-      #         sudo systemctl start docker
-      #         sudo systemctl enable docker
-      #     else
-      #         echo "Docker is already installed."
-      #     fi
-
-      # - name: Check for Docker-Compose
-      #   run: |
-      #     if ! command -v docker-compose &> /dev/null
-      #     then
-      #         echo "Docker Compose not found, installing..."
-      #         sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-      #         sudo chmod +x /usr/local/bin/docker-compose
-      #     else
-      #         echo "Docker Compose is already installed."
-      #     fi
-
       - name: Check for Maven
         run: |
           if ! command -v mvn &> /dev/null; then
@@ -55,32 +31,6 @@ jobs:
           else
               echo "Maven is already installed."
           fi
-
-      # - name: Install Java 19
-      #   run: |
-      #     # Download Adoptium Temurin JDK 19
-      #     wget https://github.com/adoptium/temurin19-binaries/releases/download/jdk-19.0.2+7/OpenJDK19U-jdk_x64_linux_hotspot_19.0.2_7.tar.gz
-          
-      #     # Create the directory for Java installations
-      #     sudo mkdir -p /usr/lib/jvm
-          
-      #     # Extract the downloaded JDK
-      #     sudo tar -xzf OpenJDK19U-jdk_x64_linux_hotspot_19.0.2_7.tar.gz -C /usr/lib/jvm
-          
-      #     # Move the JDK to the correct directory
-      #     sudo mv /usr/lib/jvm/jdk-19.0.2+7 /usr/lib/jvm/java-19-openjdk-amd64
-          
-      #     # Set up JAVA_HOME and PATH environment variables
-      #     echo "JAVA_HOME=/usr/lib/jvm/java-19-openjdk-amd64" | sudo tee -a /etc/environment
-      #     echo "export JAVA_HOME=/usr/lib/jvm/java-19-openjdk-amd64" | sudo tee -a ~/.bashrc
-      #     echo "export PATH=\$JAVA_HOME/bin:\$PATH" | sudo tee -a ~/.bashrc
-          
-      #     # Apply changes
-      #     source ~/.bashrc
-          
-      #     # Verify installation
-      #     java -version
-        
 
       - name: Validate Installation
         run: |
@@ -106,71 +56,71 @@ jobs:
           export JAVA_HOME=/usr/lib/jvm/java-19-openjdk-amd64
           export PATH=$JAVA_HOME/bin:$PATH
           ./mvnw -B package
-    
+
   deploy:
-      runs-on: self-hosted
-      needs: test
-      steps:
-        - name: Verify JAR file
-          run: |
-            echo "Verifying JAR file presence..."
-            ls -al /home/ibtahaj/spring-petclinic/target/
-            if [ -z "$(find /home/ibtahaj/spring-petclinic/target/ -name 'spring-petclinic-3.3.0-SNAPSHOT.jar')" ]; then
-              echo "JAR file not found in target directory!"
-              exit 1
-            fi
+    runs-on: self-hosted
+    needs: build
+    steps:
+      - name: Verify JAR file
+        run: |
+          echo "Verifying JAR file presence..."
+          ls -al /home/ibtahaj/spring-petclinic/target/
+          if [ -z "$(find /home/ibtahaj/spring-petclinic/target/ -name 'spring-petclinic-3.3.0-SNAPSHOT.jar')" ]; then
+            echo "JAR file not found in target directory!"
+            exit 1
+          fi
     
-        - name: Check ssh-keyscan
-          run: which ssh-keyscan || echo "ssh-keyscan not found"
+      - name: Check ssh-keyscan
+        run: which ssh-keyscan || echo "ssh-keyscan not found"
     
-        - name: Setup SSH
-          env:
-            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-            DEPLOY_SERVER: '103.151.111.190'
-          run: |
-            echo "Setting up SSH..."
-            mkdir -p ~/.ssh
-            chmod 700 ~/.ssh
-            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
-            chmod 600 ~/.ssh/id_rsa
-            echo "Scanning for SSH key..."
-            ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts || true
-            echo "Known hosts content:"
-            cat ~/.ssh/known_hosts
-            echo "SSH setup complete."
+      - name: Setup SSH
+        env:
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+          DEPLOY_SERVER: '103.151.111.190'
+        run: |
+          echo "Setting up SSH..."
+          mkdir -p ~/.ssh
+          chmod 700 ~/.ssh
+          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          echo "Scanning for SSH key..."
+          ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts || true
+          echo "Known hosts content:"
+          cat ~/.ssh/known_hosts
+          echo "SSH setup complete."
     
-        - name: Deploy application
-          env:
-            DEPLOY_SERVER: '103.151.111.190'
-            DEPLOY_PORT: '8080'
-            DEPLOY_USER: 'ibtahaj'
-            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-          run: |
-            echo "Deploying application to $DEPLOY_SERVER"
-            scp -i ~/.ssh/id_rsa /home/ibtahaj/spring-petclinic/target/spring-petclinic-3.3.0-SNAPSHOT.jar $DEPLOY_USER@$DEPLOY_SERVER:/home/ibtahaj/spring-petclinic/
-            ssh -i ~/.ssh/id_rsa $DEPLOY_USER@$DEPLOY_SERVER "java -jar /home/ibtahaj/spring-petclinic/target/spring-petclinic-3.3.0-SNAPSHOT.jar"
-            rm -f ~/.ssh/id_rsa
+      - name: Deploy application
+        env:
+          DEPLOY_SERVER: '103.151.111.190'
+          DEPLOY_USER: 'ibtahaj'
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+        run: |
+          echo "Deploying application to $DEPLOY_SERVER"
+          scp -i ~/.ssh/id_rsa /home/ibtahaj/spring-petclinic/target/spring-petclinic-3.3.0-SNAPSHOT.jar $DEPLOY_USER@$DEPLOY_SERVER:/home/ibtahaj/spring-petclinic/
+          ssh -i ~/.ssh/id_rsa $DEPLOY_USER@$DEPLOY_SERVER "java -jar /home/ibtahaj/spring-petclinic/target/spring-petclinic-3.3.0-SNAPSHOT.jar"
+          rm -f ~/.ssh/id_rsa
                       
-        - name: Wait for application to start
-          run: |
-            echo "Waiting for application to start..."
-            for i in {1..30}; do
-              if curl -s http://103.151.111.190:8080 > /dev/null; then
-                echo "Application is up!"
-                break
-              else
-                echo "Application is not up yet, retrying in 10 seconds..."
-                sleep 10
-              fi
-            done
+      - name: Wait for application to start
+        run: |
+          echo "Waiting for application to start..."
+          for i in {1..30}; do
+            if curl -s http://103.151.111.190:8080 > /dev/null; then
+              echo "Application is up!"
+              break
+            else
+              echo "Application is not up yet, retrying in 10 seconds..."
+              sleep 10
+            fi
+          done
+
   test:
-      runs-on: self-hosted
-      needs: build
-      steps:
-        - name: Check application URL
-          run: |
-            echo "Checking application URL"
-            curl -s http://103.151.111.190:8080 || exit 1
+    runs-on: self-hosted
+    needs: deploy
+    steps:
+      - name: Check application URL
+        run: |
+          echo "Checking application URL"
+          curl -s http://103.151.111.190:8080 || exit 1
   
-        - name: Run tests
-          run: ./mvnw test
+      - name: Run tests
+        run: ./mvnw test
